### ISSUE TITLE
Styling on BS5.3 is a bit off still

### ISSUE THREAD

**Issue by craigh** [RemoteDevForce/tom-select#9]
pre 5.3 changes:
<img width="246" alt="Screenshot 2023-07-26 at 7 52 25 AM" src="https://github.com/RemoteDevForce/tom-select/assets/350048/e5825c40-e901-466d-a3ae-0096891625ec">

post 5.3 changes:
<img width="228" alt="Screenshot 2023-07-26 at 7 52 21 AM" src="https://github.com/RemoteDevForce/tom-select/assets/350048/283b0d9b-7aca-4bb6-89fa-9f4ec590de11">

Outline is too heavy and drop carat is missing.

**Comment by craigh** [comment]
@Robert430404 any ideas with this one? The border width is one of the areas we were playing with to get it to compile I think? (that `calc` and `add` spot)

**Comment by craigh** [comment]
<img width="549" alt="Screenshot 2023-07-27 at 10 41 45 AM" src="https://github.com/RemoteDevForce/tom-select/assets/350048/372bd21a-bf36-4414-8f1d-0119d9d0b1ed">
Was messing with border colors on my project and see that this appears to have two borders somehow.

**Comment by craigh** [comment]
I don't know. I was using it in my own project where I imported both BS5.3 and this Tom-Select.

**Comment by craigh** [comment]
you have write access 😉

**Comment by craigh** [comment]
1. When I had to choose, I didn't know about Slim Select
2. I use Symfony. Tom Select is used as [part of one of their components](https://ux.symfony.com/autocomplete) so I thought I was choosing something with a long lifespan and support (that didn't work out so well)
3. The project previously used selectize.js and Tom-Select is a fork of that, making the transition easier.

**Comment by rjaros** [comment]
Hello @MatthewKennedy,
After making some changes regarding this issue in 2.2.6 (this commit: https://github.com/RemoteDevForce/tom-select/commit/bc141665a23abed3fd04642ac235b4dc4db0962a) there is no border at all when both "form-control" and "form-select" bootstrap classes are used.
See: https://jsfiddle.net/85b1469w/

**Comment by rjaros** [comment]
It's the same. 
https://jsfiddle.net/85b1469w/1/

**Comment by rjaros** [comment]
I'm not 100% sure, but I think using "form-control" is a better solution to the original problem (thick border). See this fiddle with TomSelect 2.2.5:
https://jsfiddle.net/85b1469w/2/

**Comment by craigh** [comment]
@rjaros can you make a PR please?

**Comment by craigh** [comment]
@rjaros please let me know if PR #15 solves the problem for you.

**Comment by rjaros** [comment]
Yes, it does.

**Comment by craigh** [comment]
@MatthewKennedy @rjaros merged and released v2.2.7

**Comment by craigh** [comment]
<img width="647" alt="Screenshot 2023-09-27 at 8 07 10 AM" src="https://github.com/RemoteDevForce/tom-select/assets/350048/85783764-a489-4ba9-a478-0fef7d282dff">
I've still got this problem ☹️ 
I am using BS 5.3.2 and tom-select 2.2.7 (both newest).

I use symfony and twig. Symfony has a bootstrap 5 "theme" that automatically styles form elements. In this case, it is adding the `form-select` class.

Additionally, we never solved the missing drop carat.

Hoping you can help @MatthewKennedy @rjaros

**Comment by rjaros** [comment]
You need both `form-control` and `form-select` classes to have correct borders and caret. Unfortunately I don't use symfony and don't know how to configure it for this case.

**Comment by craigh** [comment]
@rjaros thank you! If I add both it works as expected...

however!

The [BS 5.3 docs](https://getbootstrap.com/docs/5.3/forms/select/#default) say the following for a select element:
> Custom <select> menus need only a custom class, .form-select to trigger the custom styles

So, imo, this lib shouldn't require _both_ classes to function correctly. What do you think?

**Comment by rjaros** [comment]
I've always assumed TomSelect requires `form-control` when using Bootstrap theme, because it's used here: https://tom-select.js.org/examples/styling/ 
It would probably be better, if it works correctly without `form-control` class, but it should not break when using both.

**Comment by craigh** [comment]
> because it's used here: https://tom-select.js.org/examples/styling/

ah - but none of those are **select** inputs - they are simple **text** inputs ;-)

**Comment by rjaros** [comment]
There is nothing wrong with making some breaking changes to make the API better. As long as it will be released as TomSelect 3.0.0 :-)

**Comment by craigh** [comment]
> There is nothing wrong with making some breaking changes

It is already "broken" for me. Upgrading from BS 5.2 -> 5.3 broke this lib. I don't think fixing that is a breaking change.

**Comment by rjaros** [comment]
> It is already "broken" for me. Upgrading from BS 5.2 -> 5.3 broke this lib.

I can't agree with that. This is a fiddle with BS 5.2 and TomSelect 2.2.5 (before any changes): https://jsfiddle.net/ouchb0rq/
As you can see if using only `form-select` class there is thick border and no arrow. Adding `form-control` fixes the problem.
Upgrading to BS 5.3 makes no difference: https://jsfiddle.net/ouchb0rq/1/

**Comment by craigh** [comment]
make the same with tom-select 2.2.2

**Comment by rjaros** [comment]
It's up to the maintainer to decide: 
- whether the issue, present from the beginning, is a bug (because the styling of select control with BS theme is not documented)?
- whether fixing such issue but breaking a known workaround (`form-control` class) at the same time is a breaking change?

I just shared my opinion. I will accept any decision and I will continue to thank anyone who maintains this library :-)

**Comment by craigh** [comment]
@MatthewKennedy I am wondering if these two changes might have broken this issue:

 - https://github.com/RemoteDevForce/tom-select/pull/1/files#diff-6fcebb391c0c0951d998e4bcbac8a903fde9b3fd1cbe2f5c4119e92c81a7f11fL232-R211
 - https://github.com/RemoteDevForce/tom-select/pull/1/files#diff-6fcebb391c0c0951d998e4bcbac8a903fde9b3fd1cbe2f5c4119e92c81a7f11fL252-R235

@MatthewKennedy would you be willing to look into it?

**Comment by craigh** [comment]
[This change](https://github.com/RemoteDevForce/tom-select/commit/18a7623c68d3b750808f941b57e55380879c5777) fixes the problem for me.

This seems correct to me because in [the recent change linked above](https://github.com/RemoteDevForce/tom-select/pull/1/files#diff-6fcebb391c0c0951d998e4bcbac8a903fde9b3fd1cbe2f5c4119e92c81a7f11fL252-R235) you can see that this:

```scss
.#{$select-ns}-wrapper.form-control,
.#{$select-ns}-wrapper.form-select{
```
was changed to this:
```scss
.#{$select-ns}-wrapper {
    //...
    &.form-control, .form-select {
```
which is incorrect - the `.form-select` no longer has the `.#{$select-ns}-wrapper` prefix. 

This fix corrects that.

@MatthewKennedy @rjaros opinions?
